name: Update digital ocean firewall whitelist

on:
  push:
    branches: master
  schedule:
  - cron: "0 0 * * *"

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - name: Update whitelist
      uses: digitalocean/action-doctl@v1
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: compute firewall list
